In [1]:
import requests

cookies = {
    'enctoken': 'Cx8LKOsMvLs2pgNLp1HGCKNzLnRQkHY3sly8AyHFBN/NbOYHrK5bCKkb8XXn3xKiAFpWKioXPACESuRDmrNP/ttUD/VZC4uYpD+rSMsAL5F9WmSXIRcRZw==',
}

headers = {
    'authorization': 'enctoken Cx8LKOsMvLs2pgNLp1HGCKNzLnRQkHY3sly8AyHFBN/NbOYHrK5bCKkb8XXn3xKiAFpWKioXPACESuRDmrNP/ttUD/VZC4uYpD+rSMsAL5F9WmSXIRcRZw==',
   }

params = {
    'user_id': 'ICS357',
    'oi': '1',
    'from': '2022-01-01',
    'to': '2026-07-24',
}
token = "289545"
symbol = "NIFTY LARGEMID250"

response = requests.get(
    f'https://kite.zerodha.com/oms/instruments/historical/{token}/day',
    params=params,
    cookies=cookies,
    headers=headers,
)
response.status_code

200

In [2]:
import pandas as pd
df = pd.DataFrame(response.json()["data"]["candles"], columns=["date_time", "open", "high", "low", "close", "volume", "open_interest"])
df["date_time"] = pd.to_datetime(df["date_time"]).dt.date
df = df[["date_time", "open", "high", "low", "close", "volume"]]
df["scrip"] = symbol
df

,date_time,open,high,low,close,volume,scrip
0,2022-01-03,9940.40,9940.40,9940.40,9940.40,0,NIFTY LARGEMID250
1,2022-01-04,9996.20,9996.20,9996.20,9996.20,0,NIFTY LARGEMID250
2,2022-01-05,10029.79,10029.79,10029.79,10029.79,0,NIFTY LARGEMID250
3,2022-01-06,9982.15,9982.15,9982.15,9982.15,0,NIFTY LARGEMID250
4,2022-01-07,10019.60,10019.60,10019.60,10019.60,0,NIFTY LARGEMID250
...,...,...,...,...,...,...,...
1113,2026-07-20,16627.95,16731.30,16613.80,16711.80,0,NIFTY LARGEMID250
1114,2026-07-21,16716.70,16748.10,16685.90,16734.75,0,NIFTY LARGEMID250
1115,2026-07-22,16723.75,16724.55,16559.85,16582.05,0,NIFTY LARGEMID250
1116,2026-07-23,16529.00,16583.25,16421.50,16457.00,0,NIFTY LARGEMID250
1117,2026-07-24,16338.15,16446.15,16262.25,16407.00,0,NIFTY LARGEMID250

In [3]:
dates = ['2002-01-01', '2007-01-01','2012-01-01', '2017-01-01', '2022-01-01', '2026-07-23']
previous_date = None
dataframe=None
for date in dates:
    if previous_date is  None:
        previous_date = date
        continue
    params = {
        'user_id': 'ICS357',
        'oi': '1',
        'from': previous_date,
        'to': date,
    }

    response = requests.get(
        f'https://kite.zerodha.com/oms/instruments/historical/{token}/day',
        params=params,
        cookies=cookies,
        headers=headers,
        )
    
    #make dataframe and append to existing dataframe
    if response.status_code == 200:
        df = pd.DataFrame(response.json()["data"]["candles"], columns=["date_time", "open", "high", "low", "close", "volume", "open_interest"])
        df["date_time"] = pd.to_datetime(df["date_time"]).dt.date
        df = df[["date_time", "open", "high", "low", "close", "volume"]]
        df["scrip"] = symbol
        previous_date = date
        dataframe = pd.concat([dataframe, df], ignore_index=True).drop_duplicates().sort_values("date_time")
    else:
        print(f"Error fetching data for {previous_date} to {date}")
    
    
dataframe

,date_time,open,high,low,close,volume,scrip
0,2005-04-01,1000.00,1000.00,1000.00,1000.00,0,NIFTY LARGEMID250
1,2005-04-04,1003.40,1003.40,1003.40,1003.40,0,NIFTY LARGEMID250
2,2005-04-05,997.05,997.05,997.05,997.05,0,NIFTY LARGEMID250
3,2005-04-06,1005.20,1005.20,1005.20,1005.20,0,NIFTY LARGEMID250
4,2005-04-07,1002.30,1002.30,1002.30,1002.30,0,NIFTY LARGEMID250
...,...,...,...,...,...,...,...
5266,2026-07-17,16671.45,16698.70,16616.00,16682.65,0,NIFTY LARGEMID250
5267,2026-07-20,16627.95,16731.30,16613.80,16711.80,0,NIFTY LARGEMID250
5268,2026-07-21,16716.70,16748.10,16685.90,16734.75,0,NIFTY LARGEMID250
5269,2026-07-22,16723.75,16724.55,16559.85,16582.05,0,NIFTY LARGEMID250
5270,2026-07-23,16529.00,16583.25,16421.50,16457.00,0,NIFTY LARGEMID250

In [5]:
dataframe.to_csv("nifty_largemidcap_250_data.csv", index=False)

In [81]:
dataframe.to_parquet(f"daywise stocks\\{symbol}.parquet", index=False)
dataframe.to_parquet(f"zerodha data\\{symbol}.parquet", index=False)

In [82]:
stock_df = pd.read_parquet(f"daywise stocks\\{symbol}.parquet")
stock_df["date_time"] = pd.to_datetime(stock_df["date_time"]).dt.date
stock_df

       date_time    open    high     low   close    volume scrip
0     2003-01-01   28.95   29.25   28.75   28.86   6286866  ZEEL
1     2003-01-02   29.04   29.80   28.89   29.45  17017480  ZEEL
2     2003-01-03   29.95   30.37   29.51   29.83  18742230  ZEEL
3     2003-01-06   30.10   30.25   29.42   29.57   6101858  ZEEL
4     2003-01-07   29.69   30.33   29.52   30.23  12460844  ZEEL
...          ...     ...     ...     ...     ...       ...   ...
5794  2026-07-06  105.37  105.70  100.99  101.85  20921812  ZEEL
5795  2026-07-07  102.36  104.59  100.30  102.37  26972652  ZEEL
5796  2026-07-08  101.70  102.37   98.60   99.56  23255860  ZEEL
5797  2026-07-09   99.80  101.39   98.44   99.79  16333504  ZEEL
5798  2026-07-10  100.60  101.96   96.79   97.47  21186362  ZEEL

[5799 rows x 7 columns]

In [ ]:
pd.concat([stock_df, df], ignore_index=True).drop_duplicates().sort_values("date_time")

In [60]:
import requests

cookies = {
    'WZRK_G': '36e3221a661648bc8d17a57105c2ec53',
    'afUserId': '8d42750e-a45f-4996-950d-6b1234f9d107-p',
    'cto_bundle': 'F1bMRV9IWTZabld5TFhjMnI5UVh5b1RtUyUyRmo5akdLOXNERFljeXZnWW1GZlJ6TG1uRlRGcVlUNlBaWnBwYSUyRkI3ZnBvaHRBJTJCSFBpbDB3bFQzOFh1ZzhJc1AyUFAlMkJXZDh6UzlqbTlpSXR5MVhTMEglMkJ1R2p6SnkxOHV4b2dnSkRBMzJZMjVZY1hFVDVGdHZrWGpZJTJGbkd2VXIzamclM0QlM0Q',
    '_gcl_au': '1.1.574853467.1776837454.605105150.1782289284.1782289296',
    '_fbp': 'fb.1.1776837454422.108793647811675265.AQYAAQIB',
    'rtab-aid': 'rtab-c72f6a4ecc8a40ca93eb7854296f28a5',
    'TR-aid': 'd1ec269b7da64772b1f7b189a90db941',
    'AF_SYNC': '1783421861309',
    'ABUserCookie': 'eJwdyrEOgjAUheFXIXdmsGJby1YbAkTbAcsDgFwDEakpDibGd7f0jN9/vqBdP81oHOTAMsEJ2TN2gBTaFb3pnhhcmnNtk+RayUbLkNQ84fJWboiRckqoCNx790Af/2VxidAtt3EDq6r2FMTYBu8e17H4vCAnXBwFz/huWwqlroeA5PcHH4AozA==',
    'prod_non_trade_access_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3R5cGUiOiJjbGllbnQiLCJ0b2tlbl90eXBlIjoibm9uX3RyYWRlX2FjY2Vzc190b2tlbiIsImdtX2lkIjowLCJzb3VyY2UiOiIzIiwiZGV2aWNlX2lkIjoiYjVhNmZlNmUtZGYzZS00ZDc4LTg5NTEtN2ZlYTg3NmU0NTc0Iiwia2lkIjoibm9uX3RyYWRlX2tleV92MiIsIm9tbmVtYW5hZ2VyaWQiOjAsInByb2R1Y3RzIjp7ImRlbWF0Ijp7InN0YXR1cyI6ImFjdGl2ZSJ9LCJtZiI6eyJzdGF0dXMiOiJhY3RpdmUifX0sImlzcyI6Im5vbl90cmFkZV9sb2dpbl9zZXJ2aWNlIiwic3ViIjoiQTU3NTE1OSIsImV4cCI6MTc4NDAwMDAwOSwibmJmIjoxNzgzOTEzNjA5LCJpYXQiOjE3ODM5MTM2MDksImp0aSI6ImY1YjY1MDQ4LWRlNjItNDM5ZC05ZmY3LTI4NmJkYjkwMmNmNiIsIlRva2VuIjoiIn0.CAL4UOalUVEiha8lsvAz7unchhKGu0HGR-F8YW4nKsKnN7STHElb-9rgNYd0ztWbCqfqJ294WyjjOjl7WJkw32nfsic2qOD3obl03zTmrOlCpj_6CtuCEnF7y4bbpVqKVtxnwvKjXXO0awSyWOrntp1EDmuj81px5QwR_bWaAI7dnyeknQTuRmnP_pkb8_RyBHk-uM7nGejLRmIPBfJhEQknAT_8blAfZbYxtS1-XG9FVzuHV542xmDArYA4n29T6R67wJwHcALPgYAMm0SvAoz2bZm1LxDIXVLdt64ek0BrdiGnW71hhIcFEWM8BCbXNj0PdewPwQUBLaEhqKaj-Q',
    '_ga': 'GA1.2.1287687795.1776837454',
    '_gid': 'GA1.2.916625606.1783913792',
    '_uetsid': '0a860b507e6c11f1a5f4a5f2dd0a0431',
    '_uetvid': '28b30e803e1011f1aea60da144f5413c',
    'prod_trade_access_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3R5cGUiOiJjbGllbnQiLCJ0b2tlbl90eXBlIjoidHJhZGVfYWNjZXNzX3Rva2VuIiwiZ21faWQiOjExLCJzb3VyY2UiOiIzIiwiZGV2aWNlX2lkIjoiYjVhNmZlNmUtZGYzZS00ZDc4LTg5NTEtN2ZlYTg3NmU0NTc0Iiwia2lkIjoidHJhZGVfa2V5X3YyIiwib21uZW1hbmFnZXJpZCI6MTEsInByb2R1Y3RzIjp7ImRlbWF0Ijp7InN0YXR1cyI6ImFjdGl2ZSJ9LCJtZiI6eyJzdGF0dXMiOiJhY3RpdmUifX0sImlzcyI6InRyYWRlX2xvZ2luX3NlcnZpY2UiLCJzdWIiOiJBNTc1MTU5IiwiZXhwIjoxNzgzOTMwMDI2LCJuYmYiOjE3ODM5MTM2NDYsImlhdCI6MTc4MzkxMzY0NiwianRpIjoiYjAyYjUxNmMtMzJhMS00MWI0LTg1YjUtOTY0YzUxNTc2OGJiIiwiVG9rZW4iOiIifQ.h6Ld26I2_0oGpQ3eAmgzfxa3Z4MY_ZgcnHrmhFiDTDLqKRy6VYs7Xx3uxCCbZNyAHPy_GSPZ-OIi9HQVfPysH0fkkXF0rTwUToQh6Sxe-sbJ__2p9ChkgCYRi0YfJbT6pO3ZcAuTQpNPavfI-Hu6Tk5W24Btd2cqpVsTXKiLge0',
    'ShowMpin': '1783957027412',
    '_ga_CDX93S7LDP': 'GS2.1.s1783913790$o19$g0$t1783913827$j23$l0$h0',
}

headers = {
    'accept': '*/*',
    'accept-language': 'en-IN,en-GB;q=0.9,en-US;q=0.8,en;q=0.7',
    'content-type': 'application/json',
    'dnt': '1',
    'ect': '4g',
    'origin': 'https://www.angelone.in',
    'priority': 'u=1, i',
    'referer': 'https://www.angelone.in/trade/tradeone/chart',
    'sec-ch-ua': '"Not;A=Brand";v="8", "Chromium";v="150", "Google Chrome";v="150"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36',
    'x-consumer': 'SPARK_WEB',
    'x-requestid': 'A575159_600_1783917556781',
    'x-tokentype': 'non_trade_access_token',
    # 'cookie': 'WZRK_G=36e3221a661648bc8d17a57105c2ec53; afUserId=8d42750e-a45f-4996-950d-6b1234f9d107-p; cto_bundle=F1bMRV9IWTZabld5TFhjMnI5UVh5b1RtUyUyRmo5akdLOXNERFljeXZnWW1GZlJ6TG1uRlRGcVlUNlBaWnBwYSUyRkI3ZnBvaHRBJTJCSFBpbDB3bFQzOFh1ZzhJc1AyUFAlMkJXZDh6UzlqbTlpSXR5MVhTMEglMkJ1R2p6SnkxOHV4b2dnSkRBMzJZMjVZY1hFVDVGdHZrWGpZJTJGbkd2VXIzamclM0QlM0Q; _gcl_au=1.1.574853467.1776837454.605105150.1782289284.1782289296; _fbp=fb.1.1776837454422.108793647811675265.AQYAAQIB; rtab-aid=rtab-c72f6a4ecc8a40ca93eb7854296f28a5; TR-aid=d1ec269b7da64772b1f7b189a90db941; AF_SYNC=1783421861309; ABUserCookie=eJwdyrEOgjAUheFXIXdmsGJby1YbAkTbAcsDgFwDEakpDibGd7f0jN9/vqBdP81oHOTAMsEJ2TN2gBTaFb3pnhhcmnNtk+RayUbLkNQ84fJWboiRckqoCNx790Af/2VxidAtt3EDq6r2FMTYBu8e17H4vCAnXBwFz/huWwqlroeA5PcHH4AozA==; prod_non_trade_access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3R5cGUiOiJjbGllbnQiLCJ0b2tlbl90eXBlIjoibm9uX3RyYWRlX2FjY2Vzc190b2tlbiIsImdtX2lkIjowLCJzb3VyY2UiOiIzIiwiZGV2aWNlX2lkIjoiYjVhNmZlNmUtZGYzZS00ZDc4LTg5NTEtN2ZlYTg3NmU0NTc0Iiwia2lkIjoibm9uX3RyYWRlX2tleV92MiIsIm9tbmVtYW5hZ2VyaWQiOjAsInByb2R1Y3RzIjp7ImRlbWF0Ijp7InN0YXR1cyI6ImFjdGl2ZSJ9LCJtZiI6eyJzdGF0dXMiOiJhY3RpdmUifX0sImlzcyI6Im5vbl90cmFkZV9sb2dpbl9zZXJ2aWNlIiwic3ViIjoiQTU3NTE1OSIsImV4cCI6MTc4NDAwMDAwOSwibmJmIjoxNzgzOTEzNjA5LCJpYXQiOjE3ODM5MTM2MDksImp0aSI6ImY1YjY1MDQ4LWRlNjItNDM5ZC05ZmY3LTI4NmJkYjkwMmNmNiIsIlRva2VuIjoiIn0.CAL4UOalUVEiha8lsvAz7unchhKGu0HGR-F8YW4nKsKnN7STHElb-9rgNYd0ztWbCqfqJ294WyjjOjl7WJkw32nfsic2qOD3obl03zTmrOlCpj_6CtuCEnF7y4bbpVqKVtxnwvKjXXO0awSyWOrntp1EDmuj81px5QwR_bWaAI7dnyeknQTuRmnP_pkb8_RyBHk-uM7nGejLRmIPBfJhEQknAT_8blAfZbYxtS1-XG9FVzuHV542xmDArYA4n29T6R67wJwHcALPgYAMm0SvAoz2bZm1LxDIXVLdt64ek0BrdiGnW71hhIcFEWM8BCbXNj0PdewPwQUBLaEhqKaj-Q; _ga=GA1.2.1287687795.1776837454; _gid=GA1.2.916625606.1783913792; _uetsid=0a860b507e6c11f1a5f4a5f2dd0a0431; _uetvid=28b30e803e1011f1aea60da144f5413c; prod_trade_access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3R5cGUiOiJjbGllbnQiLCJ0b2tlbl90eXBlIjoidHJhZGVfYWNjZXNzX3Rva2VuIiwiZ21faWQiOjExLCJzb3VyY2UiOiIzIiwiZGV2aWNlX2lkIjoiYjVhNmZlNmUtZGYzZS00ZDc4LTg5NTEtN2ZlYTg3NmU0NTc0Iiwia2lkIjoidHJhZGVfa2V5X3YyIiwib21uZW1hbmFnZXJpZCI6MTEsInByb2R1Y3RzIjp7ImRlbWF0Ijp7InN0YXR1cyI6ImFjdGl2ZSJ9LCJtZiI6eyJzdGF0dXMiOiJhY3RpdmUifX0sImlzcyI6InRyYWRlX2xvZ2luX3NlcnZpY2UiLCJzdWIiOiJBNTc1MTU5IiwiZXhwIjoxNzgzOTMwMDI2LCJuYmYiOjE3ODM5MTM2NDYsImlhdCI6MTc4MzkxMzY0NiwianRpIjoiYjAyYjUxNmMtMzJhMS00MWI0LTg1YjUtOTY0YzUxNTc2OGJiIiwiVG9rZW4iOiIifQ.h6Ld26I2_0oGpQ3eAmgzfxa3Z4MY_ZgcnHrmhFiDTDLqKRy6VYs7Xx3uxCCbZNyAHPy_GSPZ-OIi9HQVfPysH0fkkXF0rTwUToQh6Sxe-sbJ__2p9ChkgCYRi0YfJbT6pO3ZcAuTQpNPavfI-Hu6Tk5W24Btd2cqpVsTXKiLge0; ShowMpin=1783957027412; _ga_CDX93S7LDP=GS2.1.s1783913790$o19$g0$t1783913827$j23$l0$h0',
}
topic = '1.1289'
json_data = {
    'action': 'Req',
    'topic': topic,
    'rtype': 'OHLCV',
    'period': 'I',
    'type': 'D',
    'duration': 1,
    'bars': 206,
    'to': '2018-06-13T05:29:59.000+05:30',
    'sort': 'ASC',
}

response = requests.post('https://www.angelone.in/charts/v2/nse/equity', cookies=cookies, headers=headers, json=json_data)

# Note: json_data will not be serialized by requests
# exactly as it was in the original request.
#data = '{"action":"Req","topic":"1.1289","rtype":"OHLCV","period":"I","type":"D","duration":1,"bars":206,"to":"2018-06-13T05:29:59.000+05:30","sort":"ASC"}'
#response = requests.post('https://www.angelone.in/charts/v2/nse/equity', cookies=cookies, headers=headers, data=data)
response.status_code

200

In [61]:
df = pd.DataFrame(response.json())
df["time"] = pd.to_datetime(df["time"], unit='ms', utc=True).apply(lambda x: x.tz_convert('Asia/Kolkata').date())
df.rename(columns={"time": "date_time"}, inplace=True)
df

      open   high    low  close   volume   date_time
0    64.41  64.86  63.66  64.32   551395  2017-08-16
1    65.54  66.65  63.39  63.81  1903548  2017-08-17
2    63.79  64.86  62.81  63.88   706098  2017-08-18
3    64.51  65.42  62.34  62.94   860614  2017-08-21
4    63.07  65.37  59.61  64.19  2700866  2017-08-22
..     ...    ...    ...    ...      ...         ...
201  63.72  66.90  63.49  64.04   276990  2018-06-07
202  64.09  65.20  62.81  63.13   442717  2018-06-08
203  63.24  64.30  62.64  63.37   350000  2018-06-11
204  63.75  63.89  62.86  63.21   210592  2018-06-12
205  63.20  64.09  63.20  63.36   110866  2018-06-13

[206 rows x 6 columns]

In [63]:
dates = ['2002-01-01', '2002-01-01','2003-01-01', '2004-01-01', '2005-01-01', '2006-01-01', '2007-01-01', '2008-01-01', 
         '2009-01-01', '2010-01-01', '2011-01-01', '2012-01-01', '2013-01-01', '2014-01-01', '2015-01-01', '2016-01-01'
         , '2017-01-01', '2018-01-01', '2019-01-01', '2020-01-01', '2021-01-01', '2022-01-01', '2023-01-01', '2024-01-01'
         , '2025-01-01', '2026-07-10']
previous_date = None
dataframe=None
for date in dates:
    if previous_date is  None:
        previous_date = date
        continue
    json_data = {
        'action': 'Req',
        'topic': topic,
        'rtype': 'OHLCV',
        'period': 'I',
        'type': 'D',
        'duration': 1,
        'bars': 461,
        'to': f'{date}T05:30:00.000+05:30',
        'sort': 'ASC',
    }

    response = requests.post('https://www.angelone.in/charts/v2/nse/equity', cookies=cookies, headers=headers, json=json_data)

    
    #make dataframe and append to existing dataframe
    if response.status_code == 200:
        df = pd.DataFrame(pd.DataFrame(response.json()))
        df["time"] = pd.to_datetime(df["time"], unit='ms', utc=True).apply(lambda x: x.tz_convert('Asia/Kolkata').date())
        df.rename(columns={"time": "date_time"}, inplace=True)
        df = df[["date_time", "open", "high", "low", "close", "volume"]]
        df["scrip"] = "GFLLIMITED"
        previous_date = date
        dataframe = pd.concat([dataframe, df], ignore_index=True).drop_duplicates().sort_values("date_time")
    else:
        print(f"Error fetching data for {previous_date} to {date}")
        previous_date = date
    
    
dataframe

       date_time   open   high    low  close   volume       scrip
0     2000-01-21   1.03   1.13   1.03   1.10  5710670  GFLLIMITED
1     2000-01-24   1.13   1.19   1.05   1.18  8800049  GFLLIMITED
2     2000-01-25   1.22   1.22   1.09   1.11  6728761  GFLLIMITED
3     2000-01-27   1.13   1.16   1.07   1.08  4165980  GFLLIMITED
4     2000-01-28   1.07   1.15   1.00   1.14  7676638  GFLLIMITED
...          ...    ...    ...    ...    ...      ...         ...
6632  2026-07-06  46.01  46.80  45.38  46.35    28588  GFLLIMITED
6633  2026-07-07  46.40  46.40  45.47  46.06    11940  GFLLIMITED
6634  2026-07-08  46.06  46.95  44.94  45.35    31686  GFLLIMITED
6635  2026-07-09  46.50  46.59  44.76  45.40    38222  GFLLIMITED
6636  2026-07-10  46.19  46.78  45.08  45.80    71752  GFLLIMITED

[6552 rows x 7 columns]

In [64]:
dataframe.to_parquet("daywise stocks\\GFLLIMITED.parquet", index=False)
dataframe.to_parquet("zerodha data\\GFLLIMITED.parquet", index=False)

In [ ]:
from datetime import datetime

ts = 1779694290534 / 1000
print(datetime.fromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S'))
pd.to_datetime(ts*1000, unit='ms', utc=True).astimezone(tz='Asia/Kolkata').to_pydatetime()

In [ ]:
from datetime import datetime
import pytz

ist = pytz.timezone('Asia/Kolkata')
dt = ist.localize(datetime(2026, 5, 4, 15, 29))
millis = int(dt.timestamp() * 1000)
millis

In [48]:
import requests
import pandas as pd

cookies = {
    'alnuyoasdasloppes': 'U2FsdGVkX18GgJuPwrRIFkOJxk4UydBSYS%2FeadLTyBID5jSq77xnpNYPqt4H9Sa2aua1Y7xNYSuWlyB2kooDVvnsruse199WpVGep5toS38DsYcnvmOuDzi5LKCWslV9DFKGJHxE66lDxfb9pjGEB%2By3fCWA3W%2BViJbZJaGeZJ8ovs%2BE%2BQDQops8ihUhX7Qf8Jyd5zDs9mJ3ANhHRfRWF3N%2F5dgfdaWmM4STcWB3TqtaOzftRZaM1Ujt2s6IIIu%2Fa24hTyUlFyUzn7zjvDb%2BmxAX2vPF2sknAvUhd8oY7mCdobf1nbtXPdxEgkw%2B3GZQ8hp8r0RuMG8C51P3bcBPtDo%2Bbq5ZvXBJ%2F78LwMzD4Vtblb37f6IFAo5MEbN%2FrWSy0vg9NNAQpfJPhaOdQBP%2B9b%2Bl8ibtrcMz9FhwWPmo%2F3zNjSSg4MOpzd7Nx6GkCU9rElzuGo1mBWJOucuuQ5ctP0r7l%2B1%2F71YVpINYsn%2Biqe%2B%2BEaEY7hJYuzgxddm1WWM7QN8GrJAvmbttZM8z0Or7LcAiWJaWsHbueZlvXUjkUFNEmYjqv1yoOwlonVR4tfDB6EV3P1WTUJPJ%2BPX9IRER7YXW3%2FGq01rt6p2nDOtHyol11FFaRyOxv1VCkNjMuQeKpIKzIyjVZF65ka6jf1U2xnSOnjj2xGuqu%2BU70i9mhMy%2BWNKdEJlqTBH4ssoKLPYx28%2FDM%2B%2BwMsaDiVa1aFUm%2FXCcHrm5xYNlwcbArM40DSp749EXx0zXh%2B2v%2FdOFc0IDdwWQGTKh7Nhjx0mNu9SVVuX9Lv1o1T9oyRrVkiQqraMmZDejvptdwoExRD7ndK7Yl5CFTKSMeRZImKUHTj9xqXaiqB5JlxkW5dVJ%2FXs6%2BNIk6GmVusRQMBOcxt5p%2Bs3Fj3bMWbHkSlklUMuwbmtMv19TZMu7gba1lmquYZL%2BMmCVbB4wg4aSxJnHxmT1k1WDEqinDDStm35YiX6MG%2B4Z%2B3MIvLhCrkFZz%2FD9ey2FcVPxzLGtqId5XDT%2FlcTggpbU4RR8nJO%2BxGljJihmtEKboTdz1MhawcgsGDTVfN4FMsrevEPVLXzsHW%2F3rbiLunm23o3w%2BYSNVX2FnxOW6FMxineDZ5kaMBFdODTzbhaXTf%2BLuNPqK%2FDzS7J5tm57ZbHe4a63EhG3ZGqy13gW6jXUlYEOBeO3MJnJU9tK3nTEGU43XHHamsvTmofAqdwZjDeJ7gxLHD292GsHetzirensIy06tY17BJYQoOvRmh3YuUl3LhiDB67FQaYjP%2FHTbLQWlJSUnJ%2FBGzTm4bkRq8ex5dAuDixFeHnWoHk3Uf74iDgA05DafeunWze%2BrbwKjZFK0H8M2b%2FJ3oIBLuNG8QWB6CMDfFwQPTVPFKJsH5cYLMq21Xm0N%2FjwGon5dDgPWwTfilVTLTd0e5QH6gmtiQVjyZkNG%2FCD%2FTEV4zZnjvqMaFvkcmakXqxGH5S77HQX0DFtnWlRmfO4jrz32DylO3tKS%2B7%2FmtSm8COYaGumOanBkesTPAxtNM5doNWXZjRG2S8LJ9SMKFnQTRpmafGFyoyIKzs6nAXnIGv3kr6h0V5QfaU%3D',
    'lhtndhgfd': 'U2FsdGVkX192plBzPsXNxFE7wJzG4bUYpTam4T9ny%2Bat%2BZ6g7l%2BWfx7kOb9diAJg6W49c63OWx8%2FMxdI%2Fpw%2BjlXLwhqt7Eznb8niZJxemvg5iy0YhDWMQsYooSTbJLhoE8ef%2FoR9qpfVUvm%2BxYdqNzaph%2BX8iMEl%2BdMJuf8JT3uGZe8xX7bKuMiUQ9jLjRGrOe4Hc1q7JgcNfclmfBUio8mb3qgaTli7NCJ7vNDlPBrVuGECS%2FzzV7rUrnQmwsFbsOiuBGCbGVzXsrUkLqIyEN26URrZRKafpPjQzndpwvCKjvgFYXCbKn7kcVzdrpYOGfN37AIZV44GSe79gyW8cf6P%2BPMgyeksOuArtGQixlr5kQGh%2B12fLZkF34vhzxMMlJxFo6TpEuHDKD6CZdGpQxla6PA5YB0rVA96Dou5y1ZQ0IQwcl2HhZTrhQEOYIf1Dz64GXPqlYFVZ4%2F1NASP5YRf%2BLwyueVNfngbYlryyPcl9YBsJhufL1KTwBMTqkmU00WY1JVFzEd2vwuoE5MdECK458JcVxmb94pTP75LXtU7sV%2B4d%2FhFtjG87c8ZoxEaJUMB16yVST4w87YomLrBhpiqIAd9rPWdwJzpvbKPcr4cc4a1E5rdmqfUtn4RvBHT5jhn3ZWAEDfpqOMgPMJAdl%2FsQdLBPqew%2BOmYbIsCao6vg1zVEtgCWQ2Y6GYMUy80ulAEJdf5x6TT7pTjzRJ7odEpPVXntvFouO2HyeFeBOXZE8EzRKctbU0Pm1msY1G43wX1RAvAJU7Rqwrht8Wik8EJrFvd%2Bx4VGLZzC4DzZLWIbhFeX4QdUpMFYrjfxZTPqJfT98ap8AQ6k%2F1liEgjeY0mtiGXcuEEMwxyhmKHHnsIobwqo7p%2FzSiXCz59uYtOe9rBZwFPBo1z123hb6E6B37Y6sm6HucFnC2uO7WB%2FOK%2FMdpk%2F5Rd4TYmV883fyGL5fkPzq%2FMvyASCjvJ6hNDEFks5E%2FiEssAzi47lLsHDbUQ%2B6UXynnVYxkH36VQuHI%2B0cTJakKN2IKC53CH6KFW0jhCDBOVX7ElKWU8aQd8VJtpK%2BSCgrQamtfMCKGshpFz6shRgPaVcfL1ws8Nzghz%2Fbwewi5u2Huf5ry4xLib91Wdn14Zih4Vk8P03npYOiTwyca2XMw%2BPfnLqsXSjlhvyrJi9EtmRMI8z72wte32SL45S3mhNSZ1pCJf1ekAJ8RPw8S1y1iewQFBqkDesCaXDIGUZA8ENVsaYFBevqabycUJH11ee%2BqOmuhBxe%2FyB1wC37o%2Fr9JVqsKDdp5%2Bqmxyz2CrtlNSyETBGtnyU%2F0PosAcip%2BdMixvbwyaw%2F6mR533JODV%2FOmy1pf3%2BJqdxmk7qROnCv9F4Bd3yagOTcc8zreDISSqMDHDkUa4DdSrljUcPH9Ipa9Z%2BZziG4gsnhED8ppKGXT%2FY8SfqJlylFAfFko5isWnxHFom%2BllCQ5YKmoE3vOHBc1gScjMKKgH2BD9dyKnMpG%2BwnjDgbVNFqRagIvB8Nvg0wiArErOg3jSbSMtXyuNbNp%2B%2BtV%2F%2BFNj5UEZFTGU9HakAHTniJFW%2FPGMPHA%3D',
    'N_KEY_SEED': 'U2FsdGVkX1%2Fz9Ngs1AIh7PMMpIIxd6suJOrFRtvLPQdCu9STNYgs8zDIJYh%2FTcX0Dl5rVVYv6bpIc%2F%2F%2By5iTyNIq8JTyT%2Ba8VVPwljwQVNCzsg7kWbbOM2PwyN%2BDAQwwziqsbovbaWfh51pMOHayQA%3D%3D',
    'SOCKET_TOKEN': 'U2FsdGVkX1%2BduMDFb2OoX0Zn5PxZLaQLhyvHVqg6EzkIguD7Dmc8%2FInmFjvD56IlJqvEtW19v52wgIjNsT8EKUwFg5CF1ogOfEeKGVr9BrG%2Bl%2BxN5eoyC8%2BbspfbbJx9lO7KTL63fbfzBDxWAsa0ybqTnweTeZvIWIT8CiRkcfv6SdFKNP9VFSPrY8Sgl7AZGmk07VCHd9s6tvDSEMViFr%2BCqzM5TVFAzfgK7A6%2Fn3KDAE%2BOJP4NGxY%2B%2F677L2xdLLNEjdJRoGMGWxskENwF1gbosm8Ym6pbvpklz5TFlIeMhRz%2BPsxFf3jRVwvfQV0aBZZso%2Bna9WjDu6zqwA7yyGSBsCYqb73BZm52lpeyj6T6Z51QFGqKtvjoibufyy3QE%2BFZJ6ACD31CmTDlsGjN5sDHCx%2FJEnVI7vjc3JhlY5OcOJUbBF86cZ67NhYdfieA0kMqygaeeWe%2Fi1H%2FwNfVO%2FgznNETnGRCvYOs8KKTY6r193qtCfRElVQJxjVvrrEsls8qT4Qf5mcmD0HYirT%2BnUNzIBuqlqzF6tC4nybOu%2FCSlokPrCunDxBWMJqtPg%2Fz0few%2Bvw%2FAGeAipw8qT%2BcKOs0P4CZcrYq3GtRm8VHeWB539g8E%2BPAoAnqFDBC4nEYG%2BLCmylsCtmm56i2JuNQTITtnS%2F0OCpquR3bCyWvFiw7TORKuyi4JKtwvL%2FM882yD0AlggUtpbHnAXIn8CJ%2BMBP96lBWwReqGlcjKWC7ZK0arcBtD42YsFwQanR%2BzC4eEG76a1QR3XWwRot9eWg0WC7OvmoSrAmdTQiGpg049%2FOu0DSUV%2FMqJ%2BOfQrXt3AhcrS5YgPBYmKN1BfV94A3GTg%3D%3D',
    'arkeyt473rfh7834cd': 'U2FsdGVkX1%2FE0JQfRrVrLblTcgKVD%2ByplEsejfMItg5cijo%2Bo9RE9y82G%2F2lucDf%2F6Cwj84jrgCCrlPgC9440NKMrUbTg9%2BQM7Rk2DDcKFtEzVzQYH8mS8DGbVkVU%2BFBWgkDCwcecVAg%2BFaw1zAQGRk1yj%2FmA1bU%2B4ZJmrSvJ%2BOHx2GPG6tsFvLSMiuWImRX6%2Fs7ZfgAza%2BGszFRTuyygavx60piCGmAWHrten5iGJwYL1wgGXwtcyEUoKtP14KUPWpA10Axsmh6HBsOlx9%2BnVUTH6F4853Cg7yTGd6eO26NgcSJCC6qkH2pXxGsbqpM2iK7izAJ1TmW%2Bw7wp18z25JqGJ1PY5XsflDhCUAByF1xrx9pOLpZnKD4brgxq2U51m4z6gniUcFBlW1BuLRGS5OeTQMoVS8JcE7VySwA7bYZCP9%2Bs53jbxMBuIgF%2BIQ72OscwOvVud6ga8yHA6JbvxcwHZiT6HRd0%2FRbeql5LQZzg8rLmlAeAsgRAWfGFZOcHZhdWA7lyGG%2BgXi1qS4jkRmbCCdwSCtnx5tEenvltMa0XuLbFwkB1zxVZPDMja55My980m77Zh50a6V1nhLO8NEMeaM6fc4Cjh4inpe9%2BWgRo5vaY%2F6TDJ4k%2F1bjY6K5%2BuNLxBAHwHKTVbzEqI2o3bScMIdIKdtnkt95sHzf4jz4WzM1AAB6qAMz17nhuf5zoyW5UaArGcm%2FKgOz1WIb%2FN%2F797q2vhbX46bKoF4ZnKVdIjH1y9q2arq%2FgY3tk8RmyA7bPXj0mRzUjrrGzFIcbH4qWHi5ROhmql7ZAHNAsw%2F%2F9jahJ4dwMV4gCK%2BuAshhOPdYSgY4oYxansEa8%2F%2FB2IGJDm%2BfAq%2FG7rgnLIVEGKTGOmfkWzbv%2BV%2FOD6EKb0bYZ5zskZFc3tQNP7zylZ5PdAfCRK9SxMTCtS31IkdbSWY%3D',
    'AUTH_SESSION_ID': 'U2FsdGVkX1%2BuTsyjjvcH7xb0%2B0w9EqlZKhL4jRK7rJXpWNVMkkIxddauCVMXsLjOezdhwyNVplhJgGFRf7NIsg%3D%3D',
    '_cfuvid': '9HXDjuIZQUAQOWmXYsgTEVb1NGy922KY4TpTQpT24SQ-1776056083.8558078-1.0.1.1-iX8olmC8GpamwZ_UiI9WH442Ttvl8f_7jbO98_zyesA',
}

headers = {
    'accept': 'application/json, text/plain, */*',
    'accept-language': 'en-IN,en-GB;q=0.9,en-US;q=0.8,en;q=0.7',
    'authorization': 'Bearer eyJraWQiOiJXTTZDLVEiLCJhbGciOiJFUzI1NiJ9.eyJleHAiOjE3NzYwODI2OTMsImlhdCI6MTc3NTc2NDIyNiwibmJmIjoxNzc1NzY0MTc2LCJzdWIiOiJ7XCJwbGF0Zm9ybVwiOlwid2ViXCIsXCJwbGF0Zm9ybVZlcnNpb25cIjpudWxsLFwib3NcIjpudWxsLFwib3NWZXJzaW9uXCI6bnVsbCxcImlwQWRkcmVzc1wiOlwiMTIyLjE2MC4xMTYuMTE1LFwiLFwibWFjQWRkcmVzc1wiOm51bGwsXCJ1c2VyQWdlbnRcIjpcIk1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS8xNDYuMC4wLjAgU2FmYXJpLzUzNy4zNlwiLFwiZ3Jvd3dVc2VyQWdlbnRcIjpudWxsLFwiZGV2aWNlSWRcIjpcImVkOGZkY2E3LWUyNDYtNWI2ZS1iZWM2LWQwNzRlMGU0M2IzMVwiLFwic2Vzc2lvbklkXCI6XCIyY2EwNjQ2ZS0xNDgyLTQxNTYtOTA2ZS1iMjAxNzc2MWEwM2RcIixcInNlc3Npb25JZElzc3VlZEF0XCI6MTc3NDMyMjMyMzIyNixcInN1cGVyQWNjb3VudElkXCI6XCJBQ0MyNzQ0MjU1MzQ0OTM1XCIsXCJ1c2VyQWNjb3VudElkXCI6XCJBQ0MyNzQ0MjU1MzQ0OTM1XCIsXCJ0eXBlXCI6XCJBVFwiLFwidG9rZW5FeHBpcnlcIjoxNzc2MDgyNjkzMjcyLFwidG9rZW5JZFwiOlwiZjIyNzQyZDMtY2VmYy00ZjEzLTkxZDMtNGVhYmIwMGM2YWRkXCIsXCJic2VVc2VySWRcIjpcIjQ1NjM0MjczOTJcIixcIm9uZUZhTW9kZVwiOlwiS05PV0xFREdFX0ZBQ1RPUlwifSIsImlzcyI6Imdyb3d3YmlsbGlvbm1pbGxlbm5pYWwifQ.uFV7jlhRfm8c1aEB9s_n4jaG7xDOyTeSv-t4qfHdtCeTOQDHqR7n4A3LXJEuK_9ZS0WpZvMcsAnoaRgNQ2XjHg',
    'referer': 'https://groww.in/charts/stocks/national-aluminium-company-ltd?exchange=NSE',
    'sec-ch-ua': '"Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"',
   
    'x-user-campaign': 'Bearer eyJraWQiOiJJQjYxMkEiLCJhbGciOiJFUzI1NiJ9.eyJleHAiOjE3NzYxNjgyMTUsImlhdCI6MTc3NjA1MDk5NiwibmJmIjoxNzc2MDUwOTQ2LCJzdWIiOiJ7XCJjcmVhdGVkQXRcIjpcIjIwMjYtMDQtMTNUMDM6Mjk6NTYuMzY0KzAwOjAwXCIsXCJ1c2VyQWNjb3VudElkXCI6XCJBQ0MyNzQ0MjU1MzQ0OTM1XCIsXCJpc1N1Y2Nlc3NcIjp0cnVlLFwic2Vzc2lvbklkXCI6XCJmZDVlZWM3Mi00Y2EzLTRjN2UtOWIzNy1iNzNlYmQxMDc1MGZcIixcImlwQWRkcmVzc1wiOlwiMTIyLjE2MC4xMTYuMTE1LFwiLFwiZGV2aWNlSWRcIjpcImVkOGZkY2E3LWUyNDYtNWI2ZS1iZWM2LWQwNzRlMGU0M2IzMVwiLFwic3VwZXJBY2NvdW50SWRcIjpcIkFDQzI3NDQyNTUzNDQ5MzVcIixcInN0b2Nrc0FjY291bnRTdGF0dXNcIjpudWxsfSIsImlzcyI6Imdyb3d3YmlsbGlvbm1pbGxlbm5pYWwifQ.HVFfa036q3xbNRR7rqwspaVMxa5X4JPsl4tRQvIlYAWR4CvK5iOnqqOSJ5dyXQJ_0jx-sW1aK9VpzSTzYbE8YA',
}
params = {
    'endTimeInMillis': '1783418340000',
    'intervalInMinutes': '1440',
    'startTimeInMillis': '978320700000',
}

response = requests.get(
    'https://groww.in/v1/api/charting_service/v4/chart/exchange/NSE/segment/CASH/RUCHISOYA',
    params=params,
    cookies=cookies,
    headers=headers,
)
response.status_code

200

In [49]:
candles = response.json()['candles']
candles_df = pd.DataFrame(candles, columns=["date_time", "open", "high", "low", "close", "volume"])
candles_df["date_time"] = pd.to_datetime(candles_df["date_time"]*1000, unit='ms', utc=True).dt.tz_convert('Asia/Kolkata').dt.strftime('%Y-%m-%d')
candles_df.fillna(0, inplace=True)
candles_df["scrip"] = "JSWSTEEL"
candles_df["volume"] = candles_df["volume"].astype(int)
candles_df

       date_time  open  high   low  close   volume     scrip
0     2002-07-19  8.30  8.30  8.05   8.22     5896  JSWSTEEL
1     2002-07-22  8.28  8.28  7.70   7.71     4380  JSWSTEEL
2     2002-07-23  7.97  8.05  7.44   7.97     3952  JSWSTEEL
3     2002-07-24  7.73  7.75  7.71   7.71     1572  JSWSTEEL
4     2002-07-25  7.70  7.85  7.48   7.78     2153  JSWSTEEL
...          ...   ...   ...   ...    ...      ...       ...
4279  2019-11-06  3.75  3.75  3.65   3.75   513515  JSWSTEEL
4280  2019-11-07  3.90  3.90  3.60   3.60  4895335  JSWSTEEL
4281  2019-11-08  3.50  3.60  3.45   3.55  3976237  JSWSTEEL
4282  2019-11-11  3.70  3.70  3.45   3.50  2287395  JSWSTEEL
4283  2019-11-13  3.50  3.55  3.35   3.35  5760839  JSWSTEEL

[4284 rows x 7 columns]

In [108]:
# candles_df.to_csv("GOLDBEES.csv", index=False)
candles_df.to_parquet("daywise stocks\\ALOKINDS.parquet", index=False)
candles_df.to_parquet("zerodha data\\ALOKINDS.parquet", index=False)

In [ ]:
df.drop_duplicates(subset=['date_time'], keep='first', inplace=True)
df.to_csv("nifty_50_data.csv", index=False)

In [27]:
from datetime import datetime
import pytz

ist = pytz.timezone('Asia/Kolkata')
dt = ist.localize(datetime(2026,7, 7, 15, 29))
millis = int(dt.timestamp() * 1000)
millis

1783418340000